package it.bugboard26;

import static org.junit.jupiter.api.Assertions.assertEquals;
import com.fasterxml.jackson.databind.JsonNode;
import java.util.UUID;

final class IssueFixtures {
  private IssueFixtures() {}

  static JsonNode create(ApiClient api, String token, String type, String priority) {
    var body = api.json("""
      {"title":"JUnit %s","description":"Issue generated by the API integration suite.","type":"%s","priority":"%s"}
      """.formatted(UUID.randomUUID(), type, priority));
    var response = api.post("/issues", token, body);
    assertEquals(201, response.status());
    return response.body().path("issue");
  }
}
